version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py run -h 0.0.0.0
    volumes:
      - 'C:\Users\zimek\Documents\GitHub\Campain_Viewer\web:/usr/src/campViewer/'
    env_file:
      - env.dev
    ports:
      - 5000:5000
    hostname: "web"
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    expose:
      - 5432
    hostname: "postgres_db"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=RPGviewer_dev

volumes:
  postgres_data: